GET http://localhost:8001/products/all
###
GET http://localhost:8001/products/3
###
GET http://localhost:8005/stock/all
###
GET http://localhost:8005/stock/product/3
###
GET http://localhost:8080/api/stock/stock/product/3
###
GET http://localhost:8888/stock-service/default
###
GET http://localhost:8080/api/stock/stock/config
###

